CREATE TABLE {roads_schema}.{roads_table} (
    {roads_id_col} INTEGER PRIMARY KEY,
    {roads_geom_col} geometry(linestring,{srid}),
    functional_class TEXT,
    path_id INTEGER,
    speed_limit INTEGER,
    {roads_oneway_col} TEXT,
    width_ft INTEGER,
    ft_bike_infra TEXT,
    ft_bike_infra_width FLOAT,
    tf_bike_infra TEXT,
    tf_bike_infra_width FLOAT,
    ft_lanes INTEGER,
    tf_lanes INTEGER,
    ft_cross_lanes INTEGER,
    tf_cross_lanes INTEGER,
    twltl_cross_lanes INTEGER,
    ft_park INTEGER,
    tf_park INTEGER,
    {roads_stress_seg_fwd} INTEGER,
    {roads_stress_cross_fwd} INTEGER,
    {roads_stress_seg_bwd} INTEGER,
    {roads_stress_cross_bwd} INTEGER,
    xwalk INTEGER
);
